import { useEffect, useRef } from "react";
import { Terminal } from "@xterm/xterm";
import { FitAddon } from "@xterm/addon-fit";
import { WebLinksAddon } from "@xterm/addon-web-links";
import { ptyBridge } from "../../../bridge/pty.bridge";
import { logBridge } from "../../../bridge/log.bridge";
import { fileBridge } from "../../../bridge/file.bridge";
import { useSessionStore } from "../../../store/session.store";

type TermEntry = {
  term: Terminal;
  fitAddon: FitAddon;
};

const MIN_SAFE_WIDTH = 320;
const MIN_SAFE_HEIGHT = 120;

function stripTerminalReports(data: string) {
  return data
    // Cursor position / device attribute / status reports generated by xterm.
    .replace(/\x1b\[\??[0-9;]*[Rcn]/g, "")
    // OSC color query replies, for example ESC ] 10;rgb:cccc/cccc/cccc BEL.
    .replace(/\x1b\](?:10|11|12|4;[0-9]+);rgb:[0-9a-fA-F/]+\x07/g, "")
    .replace(/\x1b\](?:10|11|12|4;[0-9]+);rgb:[0-9a-fA-F/]+\x1b\\/g, "");
}

function stripEchoedTerminalReports(data: string) {
  return data
    .split(/\r?\n/)
    .filter((line) => {
      const trimmed = line.trim();
      if (/^(?:;)?(?:\d+R|\d+c\d+)(?:;|$)/.test(trimmed)) return false;
      if (/^zsh: (?:command not found|no such file or directory): (?:\d+R|\d+c\d+|rgb:)/.test(trimmed)) return false;
      return true;
    })
    .join("\r\n");
}

export function usePty() {
  const terminalRef = useRef<Map<string, TermEntry>>(new Map());
  const containerRef = useRef<Map<string, HTMLDivElement>>(new Map());
  const resizeObserverRef = useRef<Map<string, ResizeObserver>>(new Map());
  const fitRafRef = useRef<Map<string, number>>(new Map());
  const bufferRef = useRef<Map<string, string>>(new Map());
  const lastResizeRef = useRef<Map<string, { cols: number; rows: number }>>(new Map());
  const replayMutedRef = useRef<Set<string>>(new Set());
  const pasteCleanupRef = useRef<Map<string, () => void>>(new Map());
  const pasteInFlightRef = useRef<Set<string>>(new Set());
  const activeSessionIdRef = useRef<string | null>(null);

  const activeSessionId = useSessionStore((state) => state.activeSessionId);
  const ingestOutput = useSessionStore((state) => state.ingestOutput);
  const markExited = useSessionStore((state) => state.markExited);
  const refreshRuntimeStatuses = useSessionStore((state) => state.refreshRuntimeStatuses);

  activeSessionIdRef.current = activeSessionId;

  function appendBuffer(sessionId: string, chunk: string) {
    const prev = bufferRef.current.get(sessionId) || "";
    const merged = prev + chunk;
    const limit = 300000;
    bufferRef.current.set(sessionId, merged.length > limit ? merged.slice(-limit) : merged);
  }

  function getPaneRect(sessionId: string) {
    const container = containerRef.current.get(sessionId);
    if (!container) return null;
    return container.getBoundingClientRect();
  }

  function safeResizePty(sessionId: string, entry: TermEntry) {
    if (activeSessionIdRef.current !== sessionId) {
      return;
    }
    const rect = getPaneRect(sessionId);
    if (!rect) return;
    if (rect.width < MIN_SAFE_WIDTH || rect.height < MIN_SAFE_HEIGHT) {
      logBridge.write({
        level: "warn",
        scope: "terminal",
        message: "Skip PTY resize: pane too small",
        meta: {
          sessionId,
          width: Math.floor(rect.width),
          height: Math.floor(rect.height)
        }
      });
      return;
    }

    const cols = Math.max(1, entry.term.cols || 120);
    const rows = Math.max(1, entry.term.rows || 36);
    ptyBridge.resize(sessionId, cols, rows);
    lastResizeRef.current.set(sessionId, { cols, rows });
  }

  function scrollToBottomIfActive(sessionId: string, term: Terminal) {
    if (activeSessionIdRef.current !== sessionId) return;
    try {
      term.scrollToBottom();
    } catch {
    }
  }

  function ensureTerminal(sessionId: string, container: HTMLDivElement) {
    const existing = terminalRef.current.get(sessionId);
    if (existing) {
      if (containerRef.current.get(sessionId) === container) {
        return;
      }
      // Remount path: rebuild xterm against the new DOM container.
      try {
        existing.term.dispose();
      } catch {
      }
      terminalRef.current.delete(sessionId);
      lastResizeRef.current.delete(sessionId);
      logBridge.write({
        level: "info",
        scope: "terminal",
        message: "Recreating xterm instance for remount",
        meta: { sessionId }
      });
    }
    logBridge.write({
      level: "info",
      scope: "terminal",
      message: "Creating xterm instance",
      meta: { sessionId }
    });

    const term = new Terminal({
      convertEol: true,
      cursorBlink: true,
      fontSize: 11,
      lineHeight: 1.18,
      letterSpacing: 0,
      fontFamily: "Menlo, Monaco, Consolas, \"Liberation Mono\", monospace",
      theme: {
        background: "#0c0c0c",
        foreground: "#cccccc",
        cursor: "#f2f2f2",
        selectionBackground: "rgba(255, 255, 255, 0.22)",
        black: "#0c0c0c",
        red: "#c50f1f",
        green: "#13a10e",
        yellow: "#c19c00",
        blue: "#0037da",
        magenta: "#881798",
        cyan: "#3a96dd",
        white: "#cccccc",
        brightBlack: "#767676",
        brightRed: "#e74856",
        brightGreen: "#16c60c",
        brightYellow: "#f9f1a5",
        brightBlue: "#3b78ff",
        brightMagenta: "#b4009e",
        brightCyan: "#61d6d6",
        brightWhite: "#f2f2f2"
      }
    });

    const fitAddon = new FitAddon();
    const linkAddon = new WebLinksAddon();
    term.loadAddon(fitAddon);
    term.loadAddon(linkAddon);
    term.open(container);
    fitAddon.fit();

    const refreshTerminal = () => {
      window.requestAnimationFrame(() => {
        try {
          scrollToBottomIfActive(sessionId, term);
          term.refresh(0, Math.max(0, term.rows - 1));
        } catch {
        }
      });
    };

    const onPaste = (event: ClipboardEvent) => {
      if (activeSessionIdRef.current !== sessionId) return;
      const session = useSessionStore.getState().sessions.find((item) => item.sessionId === sessionId);
      if (!session) return;
      if (session.provider !== "codex" && session.provider !== "gemini") return;
      if (!session.cwd) return;
      const items = Array.from(event.clipboardData?.items || []);
      const hasImage = items.some((item) => String(item.type || "").toLowerCase().startsWith("image/"));
      if (!hasImage) return;
      event.preventDefault();
      event.stopPropagation();
      if (pasteInFlightRef.current.has(sessionId)) return;
      pasteInFlightRef.current.add(sessionId);
      void fileBridge.saveAttachmentImage({
        cwd: session.cwd,
        sessionId
      }).then((result) => {
        if (!result?.ok || !result.relPath) {
          if (result?.reason !== "no-image") {
            logBridge.write({
              level: "warn",
              scope: "terminal",
              message: "Clipboard image save skipped",
              meta: { sessionId, reason: result?.reason || "unknown" }
            });
          }
          return;
        }
        ptyBridge.input(sessionId, `@${result.relPath}`);
      }).catch((error) => {
        logBridge.write({
          level: "warn",
          scope: "terminal",
          message: "Clipboard image save failed",
          meta: { sessionId, error: error instanceof Error ? error.message : String(error) }
        });
      }).finally(() => {
        pasteInFlightRef.current.delete(sessionId);
        try {
          term.focus();
        } catch {
        }
      });
    };

    const pasteTarget = term.textarea || container;
    const pasteListener = (event: Event) => onPaste(event as ClipboardEvent);
    pasteTarget.addEventListener("paste", pasteListener, true);
    const prevCleanup = pasteCleanupRef.current.get(sessionId);
    if (prevCleanup) prevCleanup();
    pasteCleanupRef.current.set(sessionId, () => {
      pasteTarget.removeEventListener("paste", pasteListener, true);
    });

    const writeReplay = (data: string, reset = false) => {
      replayMutedRef.current.add(sessionId);
      const finishReplay = () => {
        scrollToBottomIfActive(sessionId, term);
        refreshTerminal();
        window.requestAnimationFrame(() => {
          replayMutedRef.current.delete(sessionId);
        });
      };
      if (reset) {
        term.reset();
      }
      term.write(data, finishReplay);
    };

    const snapshot = stripEchoedTerminalReports(bufferRef.current.get(sessionId) || "");
    if (snapshot) {
      try {
        writeReplay(snapshot);
      } catch (error) {
        replayMutedRef.current.delete(sessionId);
        logBridge.write({
          level: "warn",
          scope: "terminal",
          message: "Initial snapshot write failed",
          meta: { sessionId, error: error instanceof Error ? error.message : String(error) }
        });
      }
    }

    ptyBridge.snapshot(sessionId).then((serverSnapshot) => {
      const data = stripEchoedTerminalReports(serverSnapshot?.data || "");
      if (!data) return;
      const localSnapshot = bufferRef.current.get(sessionId) || "";
      if (localSnapshot.length >= data.length) return;
      bufferRef.current.set(sessionId, data);
      try {
        writeReplay(data, Boolean(localSnapshot));
      } catch (error) {
        replayMutedRef.current.delete(sessionId);
        logBridge.write({
          level: "warn",
          scope: "terminal",
          message: "Server snapshot write failed",
          meta: { sessionId, error: error instanceof Error ? error.message : String(error) }
        });
      }
    }).catch((error) => {
      logBridge.write({
        level: "warn",
        scope: "terminal",
        message: "Failed to load PTY snapshot",
        meta: { sessionId, error: error instanceof Error ? error.message : String(error) }
      });
    });

    term.onData((data) => {
      if (activeSessionIdRef.current !== sessionId) return;
      if (replayMutedRef.current.has(sessionId)) return;
      const sanitized = stripTerminalReports(data);
      if (!sanitized) return;
      ptyBridge.input(sessionId, sanitized);
    });

    safeResizePty(sessionId, { term, fitAddon });

    terminalRef.current.set(sessionId, { term, fitAddon });
  }

  function setPaneRef(sessionId: string, el: HTMLDivElement | null) {
    if (!el) {
      if (!containerRef.current.has(sessionId)) return;
      logBridge.write({
        level: "info",
        scope: "terminal",
        message: "Pane unmounted",
        meta: { sessionId }
      });
      const existingObserver = resizeObserverRef.current.get(sessionId);
      if (existingObserver) {
        existingObserver.disconnect();
        resizeObserverRef.current.delete(sessionId);
      }
      const pasteCleanup = pasteCleanupRef.current.get(sessionId);
      if (pasteCleanup) {
        pasteCleanup();
        pasteCleanupRef.current.delete(sessionId);
      }
      const raf = fitRafRef.current.get(sessionId);
      if (typeof raf === "number") {
        window.cancelAnimationFrame(raf);
        fitRafRef.current.delete(sessionId);
      }
      const existingTerminal = terminalRef.current.get(sessionId);
      if (existingTerminal) {
        try {
          existingTerminal.term.dispose();
        } catch {
        }
        terminalRef.current.delete(sessionId);
        lastResizeRef.current.delete(sessionId);
        replayMutedRef.current.delete(sessionId);
      }
      containerRef.current.delete(sessionId);
      return;
    }
    if (containerRef.current.get(sessionId) === el && terminalRef.current.has(sessionId)) {
      return;
    }
    logBridge.write({
      level: "info",
      scope: "terminal",
      message: "Pane mounted",
      meta: { sessionId }
    });
    containerRef.current.set(sessionId, el);
    ensureTerminal(sessionId, el);

    const scheduleFit = () => {
      const prev = fitRafRef.current.get(sessionId);
      if (typeof prev === "number") window.cancelAnimationFrame(prev);
      const raf = window.requestAnimationFrame(() => {
        const entry = terminalRef.current.get(sessionId);
        if (!entry) return;
        entry.fitAddon.fit();
        safeResizePty(sessionId, entry);
      });
      fitRafRef.current.set(sessionId, raf);
    };

    scheduleFit();

    if (typeof ResizeObserver !== "undefined") {
      const existingObserver = resizeObserverRef.current.get(sessionId);
      if (existingObserver) existingObserver.disconnect();
      const observer = new ResizeObserver(() => scheduleFit());
      observer.observe(el);
      resizeObserverRef.current.set(sessionId, observer);
    }
  }

  function fitActiveTerminal() {
    const sid = activeSessionIdRef.current;
    if (!sid) return;
    const entry = terminalRef.current.get(sid);
    if (!entry) return;
    entry.fitAddon.fit();
    safeResizePty(sid, entry);
    scrollToBottomIfActive(sid, entry.term);
    entry.term.focus();
  }

  useEffect(() => {
    const offData = ptyBridge.onData(({ sessionId, data }) => {
      appendBuffer(sessionId, data);
      ingestOutput(sessionId, data);
      const entry = terminalRef.current.get(sessionId);
      if (entry && containerRef.current.has(sessionId)) {
        try {
          entry.term.write(data);
          scrollToBottomIfActive(sessionId, entry.term);
        } catch (error) {
          logBridge.write({
            level: "warn",
            scope: "terminal",
            message: "term.write failed",
            meta: { sessionId, error: error instanceof Error ? error.message : String(error) }
          });
        }
      }
    });

    const offExit = ptyBridge.onExit(({ sessionId, exitCode }) => {
      const line = `\r\n[process exited with code ${exitCode}]\r\n`;
      appendBuffer(sessionId, line);
      const entry = terminalRef.current.get(sessionId);
      if (entry && containerRef.current.has(sessionId)) {
        try {
          entry.term.write(line);
          scrollToBottomIfActive(sessionId, entry.term);
        } catch (error) {
          logBridge.write({
            level: "warn",
            scope: "terminal",
            message: "term.write exit line failed",
            meta: { sessionId, error: error instanceof Error ? error.message : String(error) }
          });
        }
      }
      markExited(sessionId, exitCode);
      logBridge.write({
        level: "info",
        scope: "terminal",
        message: "PTY exited",
        meta: { sessionId, exitCode }
      });
    });

    const idleTimer = window.setInterval(() => {
      refreshRuntimeStatuses();
    }, 1000);

    return () => {
      offData();
      offExit();
      window.clearInterval(idleTimer);
      for (const observer of resizeObserverRef.current.values()) {
        observer.disconnect();
      }
      for (const cleanup of pasteCleanupRef.current.values()) {
        cleanup();
      }
      for (const raf of fitRafRef.current.values()) {
        window.cancelAnimationFrame(raf);
      }
      resizeObserverRef.current.clear();
      pasteCleanupRef.current.clear();
      fitRafRef.current.clear();
      for (const { term } of terminalRef.current.values()) {
        term.dispose();
      }
      terminalRef.current.clear();
      containerRef.current.clear();
      replayMutedRef.current.clear();
    };
  }, [ingestOutput, markExited, refreshRuntimeStatuses]);

  useEffect(() => {
    fitActiveTerminal();
    const raf = window.requestAnimationFrame(() => fitActiveTerminal());
    logBridge.write({
      level: "info",
      scope: "terminal",
      message: "Active session changed",
      meta: { activeSessionId }
    });
    const onResize = () => fitActiveTerminal();
    window.addEventListener("resize", onResize);
    return () => {
      window.cancelAnimationFrame(raf);
      window.removeEventListener("resize", onResize);
    };
  }, [activeSessionId]);

  useEffect(() => {
    window.__MERGECODECLI_TEST__ = {
      getSessionBuffer: (sessionId: string) => bufferRef.current.get(sessionId) || "",
      getPaneDisplay: (sessionId: string) => {
        const el = containerRef.current.get(sessionId);
        if (!el) return null;
        return window.getComputedStyle(el).display;
      },
      getLastResize: (sessionId: string) => lastResizeRef.current.get(sessionId) || null
    };

    return () => {
      // @ts-expect-error test hook
      delete window.__MERGECODECLI_TEST__;
    };
  }, []);

  return {
    setPaneRef,
    fitActiveTerminal
  };
}
